go-webauthn/webauthn

protocol/attestation_test.go
protocol/authenticator.go
protocol/credential.go

This prevents edge case checks from not matching for example when the appid hash is nil.

fix: appid check

---

protocol/assertion_test.go
protocol/attestation.go
protocol/attestation_u2f.go
protocol/authenticator.go
protocol/credential_test.go
protocol/webauthncbor/webauthncbor.go
protocol/webauthncose/webauthncose.go
protocol/webauthncose/webauthncose_test.go
webauthn/credential_test.go

Co-authored-by: Maximilian Leibl <leibl.maximilian@gmail.com>
#	protocol/attestation_u2f.go

fix: use ctap2 cbor

---

protocol/assertion.go
protocol/authenticator.go
protocol/client.go

This encodes the RP hashes as hexidecimal and properly handles a few other errors/checks.

fix: encode hashes as hex

---

protocol/client.go

This fixes an incorrect usage of subtle.ConstantTimeCompare.

fix: incorrect usage of subtle

---

protocol/authenticator.go
protocol/authenticator_test.go

Co-authored-by: Zachary Huff <zach.huff.386@gmail.com>

fix: potential index out of range panic

---

protocol/attestation_packed.go
protocol/attestation_tpm.go
protocol/webauthncose/webauthncose.go

This minor refactor utilizes type switch assignments instead of basic switch statements. This results in less allocations. In addition it dumps the usage of fmt.Sprintf to format bytes as a string.

refactor: use type switch with assignment

---

protocol/attestation_androidkey.go
protocol/attestation_packed.go
protocol/attestation_safetynet.go
protocol/attestation_test.go
protocol/attestation_tpm.go
protocol/client.go
protocol/webauthncose/webauthncose.go
webauthn/login.go

Handle errs, simplify logic, remove checks that are not necessary.

refactor: apply several linting fixes

---

protocol/attestation_u2f.go
protocol/credential.go
protocol/extensions.go
protocol/options.go
webauthn/credential.go
webauthn/login.go
webauthn/registration.go

This automatically includes the specified appid if one of the credentials contains a credential with type fido-u2f.

feat: add with setters for appid related extensions

---

protocol/authenticator.go
protocol/options.go
webauthn/authenticator_test.go
webauthn/registration.go

Adds the residentKey protocol option which is part of Webauthn Level 2.

feat: add resident key protocol option

---

protocol/credential.go
protocol/credential_test.go
protocol/options_test.go
webauthn/credential.go

The spec requires RP's to accept all transports even unregistered/unknown ones. See https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-transports-slot.

fix: parse all transports even if unknown

---

protocol/authenticator.go

This checks the credential id length based on the spec. See https://w3c.github.io/webauthn/#attested-credential-data.

fix: check the credential id length att data

---

protocol/credential.go

The struct in question is used internally not for unmarshalling JSON (i.e. post parsing the JSON struct).

fix: unused json tag

---

webauthn/login.go

This adds discoverable login tooling previously known as resident keys. It does so via an overloaded ValidateLogin that retrieves the user object for a given UserHandle if available in the response.

feat: discoverable login

---

README.md

This relates to #2 and adds a section detailing the differences between this library and the upstream library.

docs: add differences section

---

README.md
protocol/attestation_packed.go
protocol/attestation_safetynet.go
protocol/authenticator.go

This restores the method protocol.ResidentKeyUnrequired() as an alias of the new option. The restored method is CLEARLY marked as deprecated and will be removed in the future.

revert: remove resident key unrequired method

---

README.md
protocol/webauthncose/webauthncose.go
webauthn/registration.go

This fixes a potential panic that can occur when calling ParseFIDOPublicKey because elliptic.Unamrshall can return two nil values if the

fix(webauthn): potential panic in parse fido public key

---

protocol/assertion.go
protocol/attestation_androidkey.go
protocol/attestation_apple.go
protocol/attestation_packed.go
protocol/attestation_tpm.go
protocol/attestation_u2f.go
protocol/authenticator.go
protocol/client.go

This fixes a potential panic caused by the U2F attestation format due to it returning a non protocol error. It uses the same return format as most other attestation format handlers.

fix(protocol): potential panic in u2f attestation

---

protocol/webauthncose/webauthncose_test.go

[this repost of https://github.com/duo-labs/webauthn/pull/158, after seeing https://github.com/duo-labs/webauthn/issues/155]
For a few hours I was convinced that this library (`webauthncose` package specifically) wasn't doing its job properly because my code was accepting bad signatures as valid. So I set out to write a test to capture this. Turns out: this library is doing its job, and my code was at fault!
<details>
<summary>Shameful details</summary>
<pre>
func checkWebauthnSignature(...) error {
valid, err := webauthncose.VerifySignature(key, message, sigBytes)
if !valid || err != nil {
return errors.Wrap(err, "error verifying signature")
}
}
</pre>
The bug in the above snippet: `errors.Wrap(nil, "something")` is `nil`. Which means when `valid` is `false`, `nil` is returned 🤦 …

test(protocol): add coverage to 256bit ecdsa curve

---

protocol/credential.go

Just noticed it in IDE because of weird formatting with extra space.
From duo-labs PR: https://github.com/duo-labs/webauthn/pull/151

Remove unnecessary space in ParsedCredential docs

---

protocol/assertion_test.go
protocol/attestation_test.go
protocol/base64.go
protocol/challenge.go
protocol/challenge_test.go
protocol/client.go
protocol/client_test.go
protocol/credential_test.go
protocol/options.go
protocol/options_test.go
webauthn/login.go
webauthn/registration.go

This fixes issue with wrong encoding being used for the challenge. According to the specs[^1] the challenge should be base64 url-safe encoded. Until now, the package used std encoding which uses slightly different set of characters. This was reported in the linked issue and we also encountered the same issue when testing our implementation of webauthn e2e using github.com/descope/virtualwebauthn.
The commit removes the custom type for challenge and instead passes around the challenge url-safe base64 encoded right from the point of creation. Because the string is fully valid it can be safely used in json as well as stored in redis or other possible storage implementations that might be used by the clients of the library.
I tried to keep the tests as close to the original as possible. In …

fix(challenge): urlsafe base64 encoding

---

.github/ISSUE_TEMPLATE/bug-report.yml
protocol/attestation_test.go
protocol/entities.go

This fixes an issue where the protocol.UserEntity field ID was encoded with Base64 URL Encoding with padding instead of without padding.
Fixes #97

fix(protocol): user entity id not encoded correctly

---

protocol/webauthncose/webauthncose.go

This fixes a potential nil ptr panic in the ParseFIDOPublicKey function.

fix(webauthncose): potential nil ptr in ec unmarshal

---

protocol/assertion.go
protocol/assertion_test.go
protocol/attestation.go
protocol/attestation_packed.go
protocol/credential.go
protocol/credential_test.go
protocol/errors.go
webauthn/credential.go

The transports JSON path as far as the Webauthn level 3 spec is concerned is response.transports i.e. within the response object with response.clientDataJSON and response.attestationObject. This fixes this location and allows for backwards temporary compatibility for anyone implementing the previous method. See the typedef https://w3c.github.io/webauthn/#typedefdef-publickeycredentialjson for more information.

fix(protocol): creation invalid transports path

---

webauthn/registration.go
webauthn/session.go

This includes the missing user display name value from the session data so if a relying party desires they can easily save the value during the finish registration stage for later to easily show the user. This is because the display name value should be set by the user and not the relying party.

fix(webauthn): missing user display name from session

---

webauthn/registration.go
webauthn/session.go

Turns out this was the incorrect method to handle this.

revert: fix(webauthn): missing user display name from session

---

webauthn/const.go
webauthn/login.go
webauthn/main.go
webauthn/registration.go

This adjusts the BeginLogin, BeginDiscoverableLogin, and BeginRegistration methods to invoke the Config.validate() function ensuring implementers who create a new Config manually still go through the validation process. This has potential to be a breaking change as validation can no longer be skipped but it's preferable that we account for those specific use cases in our validations. This allows us to make it easy to ensure deprecated options to be properly remapped.

fix: validate configuration on all begin funcs

---

protocol/assertion.go
protocol/credential.go

This fixes inaccessibility to parsing protocol.CredentialCreationResponse / protocol.CredentialAssertionResponse into a protocol.ParsedCredentialCreationData / protocol.ParsedCredentialAssertionData object which may prevent the use of the library with gRPC for example.

fix(protocol): expose ccr/car parse method

---

go.mod
go.sum
metadata/metadata.go

Replaces the revoke library and instead creates a library for purposes like this in the future.

build(deps): utilize github.com/go-webauthn/x

---

metadata/metadata.go
metadata/metadata_test.go
protocol/attestation.go
protocol/attestation_test.go

- For purposes of determining if an authenticator has produced a full attestation when the MDS entry for the authenticator indicates  cannot produce a full attestation, treat `attca` and `basic_full` both as full attestation types
- Add test data with an authenticator aaguid that only has `attca` type
- Make production metadata available for use in tests
Resolves #149

Treat attestation type attca as a full attestation like basic_full

---

protocol/credential.go

Mark `CredentialCreationResponse.Transports` as deprecated with doc-comments. This field was effectively deprecated in #113, but without any comments making that clear to consumers of the library.

fix(protocol): mark transports field as deprecated

---

webauthn/login.go

The different parts of the code were already in the code. Was missing this simple function (FinishDiscoverableLogin) to get methods to finish login in both cases (discoverable credentials or not discoverable).

feat(detail) : Implementing FinishDiscoverableLogin for API consistency

---

protocol/authenticator.go
protocol/webauthncbor/webauthncbor.go
protocol/webauthncose/webauthncose.go

This fixes an CBOR unmarshalling issue that was caused without properly reading the upgrade notes for a dependency upgrade. We added a note to ensure we investigate the specific use case for the new unmarshal method later.

fix(protocol): previous unmarshal functionality broken

---

protocol/entities.go
webauthn/registration_test.go

This fixes an issue where the displayName value for a user entity was omitted in error. See https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialcreationoptions-user and https://www.w3.org/TR/webauthn-3/#dictdef-publickeycredentialuserentity (and the same links for level 2).
Fixes #183

fix(protocol): display name omitted incorrectly

---

webauthn/registration.go

The timeout config for registration when using User Verification Discouraged was not set correctly.
Fixes #187

fix: timeout config not propagating

---

README.md

I think it is important to note that `credential.Authenticator.CloneWarning` should be checked (or willfully ignored). And also credential should be stored, otherwise counter checking does not really work?
Is it safe to just overwrite the credential or are there values in registration credential which are missing from the logic credential object?
Is there anything else which should be validated in business logic and is missing from the example?

Update finish loging example

---

webauthn/login.go

This pull request addresses an issue where the BackupEligible flag could be inadvertently altered during the login validation process. The following changes have been made:
- Added a check in the validateLogin function to ensure that the BackupEligible flag remains consistent.
- If the BackupEligible flag is found to be altered, an error is returned.
- Updated the validateLogin function to handle this validation step appropriately.

feat!: backup flag validation

---

webauthn/types.go

This allows setting empty require resident key and user verification values for the selection criteria.
BREAKING CHANGE: This change will change default behaviour. Previously the required resident key value was set to false, and the user verification option was set to 'preferred'.

feat!: allow empty modality values

---

protocol/assertion.go
protocol/credential.go
protocol/decoder.go

This adds methods to parse raw byte slices instead of an io.Reader via protocol.ParseCredentialCreationResponseBytes and protocol.ParseCredentialRequestResponseBytes.

feat: parse credential bytes

---

metadata/providers/memory/options.go

This fixes an issue where the functional option sets the wrong value.
Fixes #266

fix(metadata): functional opt sets wrong value

---

metadata/decode.go
metadata/providers/memory/options.go

This fixes an issue where the metadata provider closed a file that may still be in use.
Fixes #264

fix(metadata): file closed too early

---

webauthn/registration.go

This exposes useful functions for generating credential properties.

fix(webauthn): expose cred params functions

---

metadata/decode.go
protocol/attestation_androidkey_test.go
protocol/attestation_apple.go
protocol/client.go
protocol/options.go

Found minor lint errors.
* `metadata/decode.go`
* chain is nil when accessing its 0 index item. Create a new slice to avoid nil access.
* `protocol/attestation_apple.go`
* `err` has been checked not `nil` in the preceding if statement, and cannot be nil again.
* Some style errors, need a space after `//` comment.

Fix lint and style errors

---

webauthn/login.go

Using the candidate json/v2 encoder
https://github.com/go-json-experiment/json SessionData doesn't roundtrip properly through json as an empty []byte is encoded as "". Mark compatible fields as omitempty, and use len(field) == 0 instead of nil checks to be more resilient.

feat(webauthn): add partial unsupported json v2 compat

---

protocol/assertion.go
protocol/attestation_androidkey.go
protocol/attestation_packed.go
protocol/attestation_tpm.go
protocol/attestation_tpm_test.go
protocol/webauthncose/webauthncose.go

The cause was a concern found in `func (k *RSAPublicKeyData) Verify`.
The [`hasher hash.Hash`](https://github.com/go-webauthn/webauthn/blob/master/protocol/webauthncose/webauthncose.go#L126) and [`hash crypto.Hash`](https://github.com/go-webauthn/webauthn/blob/master/protocol/webauthncose/webauthncose.go#L130) come from different source, whose type can be unmatched, if the list of struct `SignatureAlgorithmDetails` is misconfigured.
So I did a little bit refactor to
1. Use `crypto.Hash` as the representation for a hash algorithm in this package, and call `New()` to generate new `hash.Hash`er once needed. To avoid the mismatch issue mentioned above.
2. Use `big.Int.FillBytes()` to ensure the parsed ec Coord is 32-byte.
3. Make `SignatureAlgorithmDetails` into a map, to provide easier way …

refactor(webauthncose): to make it more readable and usable.

---

README.md
webauthn/credential.go

This adds a new function NewCredentialFlags which is leveraged by us to derive the flags that the spec requires implementers store. The addition of this function ensures that added functionality or flags that need to be stored can relatively easily and painlessly be stored and restored by third parties.

feat(webauthn): include new credential flags func

---

protocol/attestation.go
protocol/attestation_tpm.go

fix https://github.com/go-webauthn/webauthn/issues/342

FIx TPM attestation certificate problem

---

metadata/metadata.go
protocol/attestation.go
protocol/attestation_tpm.go

This addresses formatting styles from the previous commit.

refactor(protocol): adjust formatting

---

webauthn/login.go
webauthn/login_test.go

This option customizes the challenge sent to the client. 
Can be used as a form of document signing method.
Closes #353

feat(webauthn): add WithChallenge login option

---

protocol/authenticator.go
protocol/options.go
webauthn/login.go
webauthn/registration.go

This adds support for credential mediation.
Closes #347

feat(protocol): credential mediation

---

README.md
metadata/const.go
metadata/metadata_test.go
metadata/status.go
metadata/types.go
protocol/assertion.go
protocol/assertion_test.go
protocol/attestation.go
protocol/attestation_androidkey.go
protocol/attestation_androidkey_test.go
protocol/attestation_apple.go
protocol/attestation_packed.go
protocol/attestation_packed_test.go
protocol/attestation_safetynet.go
protocol/attestation_tpm.go
protocol/attestation_tpm_test.go
protocol/attestation_u2f.go
protocol/authenticator.go
protocol/client.go
protocol/credential.go
protocol/credential_test.go
protocol/errors.go
protocol/metadata.go
protocol/options_test.go
webauthn/login.go

This adds significant improvements to the MDS3 errors and general errors helping identify the root cause of a validation errors as well as many general errors via additional information or unwrapping the inner error.
Closes #365

feat(protocol): enhance errors

---

protocol/attestation.go
protocol/metadata.go
webauthn/login.go

Instead of validating the attestation type in logins, the attestation format which is saved is checked.

fix(webauthn): login validates attestation format

---

metadata/providers/cached/util.go

This fixes an issue where the metadata cached file cannot be updated because the file was opened as read-only.
0.11.2
When initializing a `cached.Provider` with `cached.New`, if the cached file already exists and needs to be updated, the `doTruncateCopyAndSeekStart` method will fail because the file was opened as read-only.
The error happens here:
https://github.com/go-webauthn/webauthn/blob/67139112f304e5b9bf38fdc5fe9438b785fe2d56/metadata/providers/cached/util.go#L12-L14
The cached file is opened as read-only using `os.Open` (see [here](https://pkg.go.dev/os#Open)) here:
https://github.com/go-webauthn/webauthn/blob/67139112f304e5b9bf38fdc5fe9438b785fe2d56/metadata/providers/cached/util.go#L28-L30
The issue can be reproduced with the following code.
The code will run successfully the …

fix(metadata): cached file update fails without write access

---

protocol/metadata.go
webauthn/login.go

This fixes an issue where an empty AAGUID would cause a failed login when it should be left to metadata validation.

fix(webauthn): empty aaguid fails login

---

protocol/attestation.go
protocol/attestation_test.go
protocol/authenticator.go
protocol/credential.go
protocol/credential_test.go
webauthn/registration.go
webauthn/types.go

feat(protocol): verify alg param during registration
This PR adds a check that is in the [webauthn spec 7.2](https://www.w3.org/TR/webauthn/#sctn-registering-a-new-credential) 
> 16. Verify that the "alg" parameter in the credential public key in authData matches the alg attribute of one of the items in options.pubKeyCredParams.
- Store `[]CredentialParameter` in session data 
- Add the verification logic into `AttestationObject.Verify()`
- Update step numbers in the comments to reflect the new values in the spec

feat(protocol): verify alg param during registration

---

protocol/attestation.go
protocol/const.go

This adds a remapping for the cable transport which has been observed in the wild, even though it has not been ratified and only exited for a short while before it was renamed.

feat(protocol): cable transport

---

protocol/authenticator.go
protocol/authenticator_test.go

Add test cases for `AuthenticatorData`'s functions
- Re-factor tests to also check error details
- Add tests to cover failure cases
- Remove newline from 2 `ErrVerification` to be consistent with other errors

test(protocol): add test cases to authenticator_test

---

protocol/assertion.go
protocol/assertion_test.go
protocol/attestation.go
protocol/attestation_test.go
protocol/authenticator.go
protocol/authenticator_test.go
protocol/credential.go
protocol/credential_test.go
webauthn/login.go
webauthn/registration.go
webauthn/types.go

This fixes conditional create would fail.
In this case, UP and UV flags will always false.
According to WebAuthn L3 spec, UP flag will be verified when options.mediation is not set to "conditional". 
Step 15:
https://www.w3.org/TR/webauthn-3/#sctn-registering-a-new-credential
Related to #361

fix(protocol): conditional create fail

---

metadata/metadata.go

This fixes an issue with the Biometric Accuracy Descriptor types in the MDS3 structs.
Fixes #450

fix(metadata): biometric accuracy descriptor types

---

webauthn/login.go
webauthn/login_test.go

There is a bug in this check: 
if a credential in the middle of `session.AllowedCredentialIDs` does not exist in `credentials`, `credentialsOwned` will be set to `false`, and `validateLogin` is supposed to return the error "User does not own all credentials from the allowedCredentialList". However, since the outer loop continues, if the last credential in `session.AllowedCredentialIDs` exist in `credentials`, `credentialsOwned` will be overwritten to `True`.
One option is to fix this, but I'd suggest that we remove this check entirely since
1. It's not specified in the webauthn specs
2. It's a bit redundant since both `session.AllowedCredentialIDs` and `credentials` are constructed on the server side

fix(webauthn): fix check for the full allowedCredentials in validateLogin

---

protocol/attestation_tpm.go

This adds the newly certified NSING TPM manufacturer to the supported list.

feat(protocol): update tpm manufacturers

---

README.md
protocol/attestation.go
protocol/metadata.go
webauthn/login.go

The attestation format none does not include attestation data and therefore cannot be validated against MDS3 metadata. Previously the login flow attempted to validate it, which caused unnecessary failures for authenticators using the none format. This change ensures that none is explicitly exempt from MDS3 validation, allowing logins with such authenticators to succeed as expected. The registration flow already implements this measure.
Fixes #387

fix(webauthn): skip mds validation for none format
